language: c
compiler:
  - gcc
  - clang
env:
  # - MRUBY_VERSION=1.3.0
  - MRUBY_VERSION=master
# matrix:
#   allow_failures:
#     - env: MRUBY_VERSION=master
branches:
  only:
    - master
addons:
  apt:
    packages:
      - rake
      # - psmisc
      - bison
      - git
      - gperf

script:
  - rake test
